
version: '3.8'

services:
  postgres_ex00:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: lgiband # ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: mysecretpassword # ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: piscineds # ${POSTGRES_DB:-postgres}
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    pgdata:
